export { default as About } from './About';
export { default as Blog } from './Blog';
export { default as Contacts } from './Contacts';
export { default as Footer} from './Footer';
export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Pricing } from './Pricing';
export { default as Services } from './Services';
export { default as Teams } from './Teams';
export { default as Testimonials } from './Testimonials';
export { default as Works } from './Works';